name: Count Plugins

on:
  push:
    branches:
      - main

jobs:
  count-plugins:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Count plugins in Plugins List
      id: count_pinned
      run: echo "::set-output name=plugin_count::$(grep -o '### \[' README.md | wc -l)"

    - name: Count plugins in Non Pinned Plugins
      id: count_non_pinned
      run: echo "::set-output name=non_pinned_plugin_count::$(grep -o '### \[' README.md | wc -l)"

    - name: Create JSON file with counts
      run: |
        echo "{ \"plugin_count\": \"${{ steps.count_pinned.outputs.plugin_count }}\", \"non_pinned_plugin_count\": \"${{ steps.count_non_pinned.outputs.non_pinned_plugin_count }}\" }" > plugin-count.json

    - name: Commit JSON file
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git add plugin-count.json
        git commit -m "Update plugin count"
        git push
